In [38]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [39]:
data = pd.read_csv("D:/Datasets/world_data.csv")
data

Unnamed: 0       artist_name                                track_name  \
0              0       Post Malone                                   Circles   
1              1      Travis Scott                       HIGHEST IN THE ROOM   
2              2        Juice WRLD  Bandit (with YoungBoy Never Broke Again)   
3              3    Arizona Zervas                                   ROXANNE   
4              4      Selena Gomez                       Lose You To Love Me   
...          ...               ...                                       ...   
9315        9315          Griselda                       Cruiser Weight Coke   
9316        9316        Koe Wetzel                                 Powerball   
9317        9317        Miky Woodz                             Forever Happy   
9318        9318             Bazzi                              Live Forever   
9319        9319  Alyssa Stanfield                                     Woman   

                    track_id  popularity  danceability  energy  key  loudness  \
0     21jGcNKet2qwijlDFuPiPb          99         0.695   0.762    0    -3.497   
1     3eekarcy7kvN4yt5ZFzltW          98         0.598   0.427    7    -8.764   
2     6Gg1gjgKi2AK4e0qzsR7sd          93         0.474   0.631    5    -5.884   
3     696DnlkuDOXcMAnKlTgXXK          97         0.621   0.601    6    -5.616   
4     1HfMVBKM75vxSfsQ5VefZ5          98         0.505   0.340    4    -9.005   
...                      ...         ...           ...     ...  ...       ...   
9315  5miZ7ZA8XJX0zGaTmtyzXn          55         0.728   0.809    3    -5.678   
9316  0cC187gu6Kcdr5VH7qxq4W          52         0.456   0.512    0    -8.650   
9317  3Q8848wMFrcBiny6lVl4l0          66         0.580   0.716   11    -3.928   
9318  3QDnzbpwnVPhx314RDZotp          56         0.572   0.664    1    -5.498   
9319  2fZuRlho8703287Kwz1jut          61         0.225   0.404    0   -19.001   

      mode  speechiness  acousticness  instrumentalness  liveness  valence  \
0        1       0.0395       0.19200          0.002440    0.0863   0.5530   
1        0       0.0317       0.05460          0.000006    0.2100   0.0605   
2        0       0.3430       0.06870          0.000000    0.1320   0.4250   
3        0       0.1480       0.05220          0.000000    0.4600   0.4570   
4        1       0.0438       0.57600          0.000000    0.2100   0.0916   
...    ...          ...           ...               ...       ...      ...   
9315     1       0.4350       0.25700          0.000000    0.3810   0.5990   
9316     1       0.0381       0.00846          0.000000    0.1650   0.0951   
9317     0       0.0852       0.29300          0.000000    0.1290   0.5090   
9318     1       0.0610       0.24300          0.000024    0.0614   0.5390   
9319     1       0.0404       0.72300          0.355000    0.1010   0.2930   

        tempo  duration_ms  time_signature  
0     120.042       215280               4  
1      76.469       175721               4  
2     180.051       189323               4  
3     116.735       163636               5  
4     101.993       206459               4  
...       ...          ...             ...  
9315  130.018       232951               4  
9316  130.072       255157               4  
9317  111.897       183093               5  
9318  169.822       152471               4  
9319  144.145       263830               3  

[9320 rows x 18 columns]

In [40]:
data.isnull().sum()

Unnamed: 0          0
artist_name         0
track_name          0
track_id            0
popularity          0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
duration_ms         0
time_signature      0
dtype: int64

In [41]:
data.columns

Index(['Unnamed: 0', 'artist_name', 'track_name', 'track_id', 'popularity',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'duration_ms', 'time_signature'],
      dtype='object')

In [63]:
df = data.head(100)
df

Unnamed: 0          artist_name                                track_name  \
0            0          Post Malone                                   Circles   
1            1         Travis Scott                       HIGHEST IN THE ROOM   
2            2           Juice WRLD  Bandit (with YoungBoy Never Broke Again)   
3            3       Arizona Zervas                                   ROXANNE   
4            4         Selena Gomez                       Lose You To Love Me   
..         ...                  ...                                       ...   
95          95               Regard                                   Ride It   
96          96  The Black Eyed Peas                 RITMO (Bad Boys For Life)   
97          97        PARTYNEXTDOOR                       Loyal (feat. Drake)   
98          98  Megan Thee Stallion                  Cash Shit (feat. DaBaby)   
99          99         Idina Menzel                          Into the Unknown   

                  track_id  popularity  danceability  energy  key  loudness  \
0   21jGcNKet2qwijlDFuPiPb          99         0.695   0.762    0    -3.497   
1   3eekarcy7kvN4yt5ZFzltW          98         0.598   0.427    7    -8.764   
2   6Gg1gjgKi2AK4e0qzsR7sd          93         0.474   0.631    5    -5.884   
3   696DnlkuDOXcMAnKlTgXXK          97         0.621   0.601    6    -5.616   
4   1HfMVBKM75vxSfsQ5VefZ5          98         0.505   0.340    4    -9.005   
..                     ...         ...           ...     ...  ...       ...   
95  2tnVG71enUj33Ic2nFN6kZ          95         0.882   0.780    0    -4.256   
96  6cy3ki60hLwimwIje7tALf          97         0.721   0.716   10    -7.037   
97  5bvnqVuq7UFl0txSlHpsfS          86         0.866   0.530    0    -6.347   
98  2rMAtCaTj16NptyVfEIeAC          81         0.921   0.635    1    -4.904   
99  3Z0oQ8r78OUaHvGPiDBR3W          86         0.323   0.405   10    -8.533   

    mode  speechiness  acousticness  instrumentalness  liveness  valence  \
0      1       0.0395        0.1920          0.002440    0.0863   0.5530   
1      0       0.0317        0.0546          0.000006    0.2100   0.0605   
2      0       0.3430        0.0687          0.000000    0.1320   0.4250   
3      0       0.1480        0.0522          0.000000    0.4600   0.4570   
4      1       0.0438        0.5760          0.000000    0.2100   0.0916   
..   ...          ...           ...               ...       ...      ...   
95     1       0.0939        0.1590          0.000052    0.0973   0.8670   
96     0       0.0657        0.0334          0.000840    0.2370   0.6670   
97     0       0.0495        0.5170          0.001590    0.0946   0.2030   
98     1       0.4160        0.0218          0.000000    0.0946   0.5490   
99     0       0.0413        0.8490          0.000544    0.1380   0.2740   

      tempo  duration_ms  time_signature  
0   120.042       215280               4  
1    76.469       175721               4  
2   180.051       189323               4  
3   116.735       163636               5  
4   101.993       206459               4  
..      ...          ...             ...  
95  117.945       157606               4  
96  104.994       221714               4  
97  104.952       197973               4  
98  130.028       192540               4  
99  145.104       194848               5  

[100 rows x 18 columns]

In [64]:
y = df["popularity"].values
y

array([ 99,  98,  93,  97,  98,  98,  97, 100,  91,  90,  96,  89,  93,
        95,  91,  92,  98,  88,  91,  96,  88,  90,  97,  93,  92,  87,
        89,  91,  91,  87,  88,  87,  86,  88,  93,  94,  87,  91,  84,
        87,  85,  87,  92,  89,  86,  85,  94,  88,  96,  92,  90,  85,
        91,  93,  89,  85,  85,  88,  92,  88,  84,  84,  88,  85,  84,
        85,  90,  84,  87,  93,  84,  88,  93,  88,  93,  82,  88,  85,
        84,  82,  88,  88,  89,  85,  83,  88,  88,  91,  85,  85,  84,
        88,  88,  85,  88,  95,  97,  86,  81,  86], dtype=int64)

In [65]:
x = df.iloc[:,[5,6,8,10,11,12,13,14,15]].values
x

array([[ 6.95000e-01,  7.62000e-01, -3.49700e+00,  3.95000e-02,
         1.92000e-01,  2.44000e-03,  8.63000e-02,  5.53000e-01,
         1.20042e+02],
       [ 5.98000e-01,  4.27000e-01, -8.76400e+00,  3.17000e-02,
         5.46000e-02,  5.83000e-06,  2.10000e-01,  6.05000e-02,
         7.64690e+01],
       [ 4.74000e-01,  6.31000e-01, -5.88400e+00,  3.43000e-01,
         6.87000e-02,  0.00000e+00,  1.32000e-01,  4.25000e-01,
         1.80051e+02],
       [ 6.21000e-01,  6.01000e-01, -5.61600e+00,  1.48000e-01,
         5.22000e-02,  0.00000e+00,  4.60000e-01,  4.57000e-01,
         1.16735e+02],
       [ 5.05000e-01,  3.40000e-01, -9.00500e+00,  4.38000e-02,
         5.76000e-01,  0.00000e+00,  2.10000e-01,  9.16000e-02,
         1.01993e+02],
       [ 7.04000e-01,  2.25000e-01, -1.44540e+01,  9.94000e-02,
         9.02000e-01,  6.57000e-01,  1.06000e-01,  2.43000e-01,
         1.20006e+02],
       [ 7.78000e-01,  5.59000e-01, -7.10900e+00,  7.76000e-02,
         1.28000e-01,  0.00000

In [66]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
x

array([[-4.87259088e-02,  1.16147985e+00,  1.19816716e+00,
        -9.25695644e-01, -9.77523378e-02, -8.79782767e-02,
        -5.44461236e-01,  3.86939326e-01, -1.93745150e-01],
       [-7.09762714e-01, -1.25571435e+00, -1.08352378e+00,
        -9.84955238e-01, -7.05610962e-01, -1.24576391e-01,
         3.61704402e-01, -1.95651814e+00, -1.50208618e+00],
       [-1.55479945e+00,  2.16248687e-01,  1.64106733e-01,
         1.38011037e+00, -6.43232457e-01, -1.24664046e-01,
        -2.09685410e-01, -2.22121702e-01,  1.60811006e+00],
       [-5.53022028e-01, -2.16465153e-04,  2.80205683e-01,
        -1.01379491e-01, -7.16228580e-01, -1.24664046e-01,
         2.19308201e+00, -6.98564449e-02, -2.93042508e-01],
       [-1.34354027e+00, -1.88346329e+00, -1.18792619e+00,
        -8.93026893e-01,  1.60106652e+00, -1.24664046e-01,
         3.61704402e-01, -1.80853535e+00, -7.35691935e-01],
       [ 1.26074030e-02, -2.71324638e+00, -3.54846045e+00,
        -4.70612348e-01,  3.04329295e+00,  9.753430

In [67]:
from sklearn.model_selection import train_test_split

In [68]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = .25,random_state = 42)

In [69]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier

In [70]:
log_clf = LogisticRegression()
rnd_clf = RandomForestClassifier()
svm_clf = svm.SVC()
nbg_clf = GaussianNB()
dec_clf = DecisionTreeClassifier()

In [71]:
for clf in(log_clf,nbg_clf,svm_clf,rnd_clf,dec_clf):
    clf.fit(x_train,y_train)
    y_pred = clf.predict(x_test)
    print(clf.__class__.__name__,accuracy_score(y_test,y_pred))

LogisticRegression 0.28
GaussianNB 0.12
SVC 0.2
RandomForestClassifier 0.12
DecisionTreeClassifier 0.12


In [72]:
from sklearn.ensemble import BaggingClassifier

In [74]:
bagg_nb_clf = BaggingClassifier(LogisticRegression(),n_estimators = 500, max_samples = 10, bootstrap = True, n_jobs = 1, oob_score = True, max_features = 0.7)
bagg_nb_clf.fit(x_train,y_train)
y_pred0 = bagg_nb_clf.predict(x_test)
print("Accuracy by using bagging logistic is : ",accuracy_score(y_test,y_pred0))

C:\Users\GOKUL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\GOKUL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Accuracy by using bagging logistic is :  0.2


In [77]:
bagg_nb_clf = BaggingClassifier(GaussianNB(),n_estimators = 500, max_samples = 10, bootstrap = True, n_jobs = 1, oob_score = True, max_features = 0.7)
bagg_nb_clf.fit(x_train,y_train)
y_pred0 = bagg_nb_clf.predict(x_test)
print("Accuracy by using bagging GNB is : ",accuracy_score(y_test,y_pred0))

ZeroDivisionError: Weights sum to zero, can't be normalized

In [78]:
bagg_nb_clf = BaggingClassifier(DecisionTreeClassifier(),n_estimators = 500, max_samples = 10, bootstrap = True, n_jobs = 1, oob_score = True, max_features = 0.7)
bagg_nb_clf.fit(x_train,y_train)
y_pred0 = bagg_nb_clf.predict(x_test)
print("Accuracy by using bagging decision tree is : ",accuracy_score(y_test,y_pred0))

Accuracy by using bagging decision tree is :  0.2


In [79]:
bagg_nb_clf = BaggingClassifier(RandomForestClassifier(),n_estimators = 500, max_samples = 10, bootstrap = True, n_jobs = 1, oob_score = True, max_features = 0.7)
bagg_nb_clf.fit(x_train,y_train)
y_pred0 = bagg_nb_clf.predict(x_test)
print("Accuracy by using bagging random forest classifier is : ",accuracy_score(y_test,y_pred0))

Accuracy by using bagging random forest classifier is :  0.2


In [80]:
bagg_nb_clf = BaggingClassifier(svm.SVC(),n_estimators = 500, max_samples = 10, bootstrap = True, n_jobs = 1, oob_score = True, max_features = 0.7)
bagg_nb_clf.fit(x_train,y_train)
y_pred0 = bagg_nb_clf.predict(x_test)
print("Accuracy by using bagging svm is : ",accuracy_score(y_test,y_pred0))

Accuracy by using bagging svm is :  0.08
