In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
data = pd.read_csv("C:/Users/GOKUL/Downloads/diamonds.csv")
data

Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0               1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95   
1               2   0.21    Premium     E     SI1   59.8   61.0    326  3.89   
2               3   0.23       Good     E     VS1   56.9   65.0    327  4.05   
3               4   0.29    Premium     I     VS2   62.4   58.0    334  4.20   
4               5   0.31       Good     J     SI2   63.3   58.0    335  4.34   
...           ...    ...        ...   ...     ...    ...    ...    ...   ...   
53935       53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75   
53936       53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69   
53937       53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66   
53938       53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15   
53939       53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83   

          y     z  
0      3.98  2.43  
1      3.84  2.31  
2      4.07  2.31  
3      4.23  2.63  
4      4.35  2.75  
...     ...   ...  
53935  5.76  3.50  
53936  5.75  3.61  
53937  5.68  3.56  
53938  6.12  3.74  
53939  5.87  3.64  

[53940 rows x 11 columns]

In [3]:
data.columns

Index(['Unnamed: 0', 'carat', 'cut', 'color', 'clarity', 'depth', 'table',
       'price', 'x', 'y', 'z'],
      dtype='object')

In [4]:
data.isnull().sum()

Unnamed: 0    0
carat         0
cut           0
color         0
clarity       0
depth         0
table         0
price         0
x             0
y             0
z             0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data["cut"]=le.fit_transform(data["cut"])
data["color"]=le.fit_transform(data["color"])
data["clarity"]=le.fit_transform(data["clarity"])

data

Unnamed: 0  carat  cut  color  clarity  depth  table  price     x  \
0               1   0.23    2      1        3   61.5   55.0    326  3.95   
1               2   0.21    3      1        2   59.8   61.0    326  3.89   
2               3   0.23    1      1        4   56.9   65.0    327  4.05   
3               4   0.29    3      5        5   62.4   58.0    334  4.20   
4               5   0.31    1      6        3   63.3   58.0    335  4.34   
...           ...    ...  ...    ...      ...    ...    ...    ...   ...   
53935       53936   0.72    2      0        2   60.8   57.0   2757  5.75   
53936       53937   0.72    1      0        2   63.1   55.0   2757  5.69   
53937       53938   0.70    4      0        2   62.8   60.0   2757  5.66   
53938       53939   0.86    3      4        3   61.0   58.0   2757  6.15   
53939       53940   0.75    2      0        3   62.2   55.0   2757  5.83   

          y     z  
0      3.98  2.43  
1      3.84  2.31  
2      4.07  2.31  
3      4.23  2.63  
4      4.35  2.75  
...     ...   ...  
53935  5.76  3.50  
53936  5.75  3.61  
53937  5.68  3.56  
53938  6.12  3.74  
53939  5.87  3.64  

[53940 rows x 11 columns]

In [6]:
y = data["price"].values
y

array([ 326,  326,  327, ..., 2757, 2757, 2757], dtype=int64)

In [7]:
x= data.drop(["price",'Unnamed: 0'],axis = 1).values
x

array([[0.23, 2.  , 1.  , ..., 3.95, 3.98, 2.43],
       [0.21, 3.  , 1.  , ..., 3.89, 3.84, 2.31],
       [0.23, 1.  , 1.  , ..., 4.05, 4.07, 2.31],
       ...,
       [0.7 , 4.  , 0.  , ..., 5.66, 5.68, 3.56],
       [0.86, 3.  , 4.  , ..., 6.15, 6.12, 3.74],
       [0.75, 2.  , 0.  , ..., 5.83, 5.87, 3.64]])

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
x

array([[-1.19816781, -0.53809897, -0.93716275, ..., -1.58783745,
        -1.53619556, -1.57112919],
       [-1.24036129,  0.43494935, -0.93716275, ..., -1.64132529,
        -1.65877419, -1.74117497],
       [-1.19816781, -1.51114729, -0.93716275, ..., -1.49869105,
        -1.45739502, -1.74117497],
       ...,
       [-0.20662095,  1.40799767, -1.52502147, ..., -0.06343409,
        -0.04774083,  0.03013526],
       [ 0.13092691,  0.43494935,  0.8264134 , ...,  0.37338325,
         0.33750627,  0.28520393],
       [-0.10113725, -0.53809897, -1.52502147, ...,  0.08811478,
         0.11861587,  0.14349912]])

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=1/4,random_state=4)

In [10]:
from sklearn.ensemble import RandomForestRegressor
clf = RandomForestRegressor(n_estimators = 100,random_state = 5)
clf.fit(x_train,y_train)

RandomForestRegressor(random_state=5)

In [11]:
y_pred = clf.predict(x_test)
y_pred

array([ 2178.3 ,   617.44,  4474.44, ...,   611.23, 10370.62,  1768.71])

In [12]:
from sklearn.metrics import r2_score  # to find the accuracy
score = r2_score(y_test,y_pred)
score

0.9814205796035884

In [13]:
y_predall = pd.DataFrame(y_pred)
y_predall

0
0       2178.30
1        617.44
2       4474.44
3       2599.39
4       3752.15
...         ...
13480   2928.51
13481    771.14
13482    611.23
13483  10370.62
13484   1768.71

[13485 rows x 1 columns]

In [14]:
newa = pd.concat([data,y_predall],axis=1)
newa

Unnamed: 0  carat  cut  color  clarity  depth  table  price     x  \
0               1   0.23    2      1        3   61.5   55.0    326  3.95   
1               2   0.21    3      1        2   59.8   61.0    326  3.89   
2               3   0.23    1      1        4   56.9   65.0    327  4.05   
3               4   0.29    3      5        5   62.4   58.0    334  4.20   
4               5   0.31    1      6        3   63.3   58.0    335  4.34   
...           ...    ...  ...    ...      ...    ...    ...    ...   ...   
53935       53936   0.72    2      0        2   60.8   57.0   2757  5.75   
53936       53937   0.72    1      0        2   63.1   55.0   2757  5.69   
53937       53938   0.70    4      0        2   62.8   60.0   2757  5.66   
53938       53939   0.86    3      4        3   61.0   58.0   2757  6.15   
53939       53940   0.75    2      0        3   62.2   55.0   2757  5.83   

          y     z        0  
0      3.98  2.43  2178.30  
1      3.84  2.31   617.44  
2      4.07  2.31  4474.44  
3      4.23  2.63  2599.39  
4      4.35  2.75  3752.15  
...     ...   ...      ...  
53935  5.76  3.50      NaN  
53936  5.75  3.61      NaN  
53937  5.68  3.56      NaN  
53938  6.12  3.74      NaN  
53939  5.87  3.64      NaN  

[53940 rows x 12 columns]

In [15]:
newa.rename(columns={0:"Predictions"},inplace=True)
newa

Unnamed: 0  carat  cut  color  clarity  depth  table  price     x  \
0               1   0.23    2      1        3   61.5   55.0    326  3.95   
1               2   0.21    3      1        2   59.8   61.0    326  3.89   
2               3   0.23    1      1        4   56.9   65.0    327  4.05   
3               4   0.29    3      5        5   62.4   58.0    334  4.20   
4               5   0.31    1      6        3   63.3   58.0    335  4.34   
...           ...    ...  ...    ...      ...    ...    ...    ...   ...   
53935       53936   0.72    2      0        2   60.8   57.0   2757  5.75   
53936       53937   0.72    1      0        2   63.1   55.0   2757  5.69   
53937       53938   0.70    4      0        2   62.8   60.0   2757  5.66   
53938       53939   0.86    3      4        3   61.0   58.0   2757  6.15   
53939       53940   0.75    2      0        3   62.2   55.0   2757  5.83   

          y     z  Predictions  
0      3.98  2.43      2178.30  
1      3.84  2.31       617.44  
2      4.07  2.31      4474.44  
3      4.23  2.63      2599.39  
4      4.35  2.75      3752.15  
...     ...   ...          ...  
53935  5.76  3.50          NaN  
53936  5.75  3.61          NaN  
53937  5.68  3.56          NaN  
53938  6.12  3.74          NaN  
53939  5.87  3.64          NaN  

[53940 rows x 12 columns]