In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [34]:
data1 = pd.read_csv("C:/Users/GOKUL/Downloads/diamonds.csv")
data1

Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0               1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95   
1               2   0.21    Premium     E     SI1   59.8   61.0    326  3.89   
2               3   0.23       Good     E     VS1   56.9   65.0    327  4.05   
3               4   0.29    Premium     I     VS2   62.4   58.0    334  4.20   
4               5   0.31       Good     J     SI2   63.3   58.0    335  4.34   
...           ...    ...        ...   ...     ...    ...    ...    ...   ...   
53935       53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75   
53936       53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69   
53937       53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66   
53938       53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15   
53939       53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83   

          y     z  
0      3.98  2.43  
1      3.84  2.31  
2      4.07  2.31  
3      4.23  2.63  
4      4.35  2.75  
...     ...   ...  
53935  5.76  3.50  
53936  5.75  3.61  
53937  5.68  3.56  
53938  6.12  3.74  
53939  5.87  3.64  

[53940 rows x 11 columns]

In [ ]:
## The aim is to predict the prices of diamond based on different parameters

In [36]:
data1.isnull().sum()

Unnamed: 0    0
carat         0
cut           0
color         0
clarity       0
depth         0
table         0
price         0
x             0
y             0
z             0
dtype: int64

In [37]:
data1.columns

Index(['Unnamed: 0', 'carat', 'cut', 'color', 'clarity', 'depth', 'table',
       'price', 'x', 'y', 'z'],
      dtype='object')

In [38]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data1["cut"]=le.fit_transform(data1["cut"])
data1["color"]=le.fit_transform(data1["color"])
data1["clarity"]=le.fit_transform(data1["clarity"])

data1

Unnamed: 0  carat  cut  color  clarity  depth  table  price     x  \
0               1   0.23    2      1        3   61.5   55.0    326  3.95   
1               2   0.21    3      1        2   59.8   61.0    326  3.89   
2               3   0.23    1      1        4   56.9   65.0    327  4.05   
3               4   0.29    3      5        5   62.4   58.0    334  4.20   
4               5   0.31    1      6        3   63.3   58.0    335  4.34   
...           ...    ...  ...    ...      ...    ...    ...    ...   ...   
53935       53936   0.72    2      0        2   60.8   57.0   2757  5.75   
53936       53937   0.72    1      0        2   63.1   55.0   2757  5.69   
53937       53938   0.70    4      0        2   62.8   60.0   2757  5.66   
53938       53939   0.86    3      4        3   61.0   58.0   2757  6.15   
53939       53940   0.75    2      0        3   62.2   55.0   2757  5.83   

          y     z  
0      3.98  2.43  
1      3.84  2.31  
2      4.07  2.31  
3      4.23  2.63  
4      4.35  2.75  
...     ...   ...  
53935  5.76  3.50  
53936  5.75  3.61  
53937  5.68  3.56  
53938  6.12  3.74  
53939  5.87  3.64  

[53940 rows x 11 columns]

In [40]:
y1 = data1["price"].values
y1

array([ 326,  326,  327, ..., 2757, 2757, 2757], dtype=int64)

In [41]:
x1 = data1.drop(["price"],axis = 1).values
x1

array([[1.0000e+00, 2.3000e-01, 2.0000e+00, ..., 3.9500e+00, 3.9800e+00,
        2.4300e+00],
       [2.0000e+00, 2.1000e-01, 3.0000e+00, ..., 3.8900e+00, 3.8400e+00,
        2.3100e+00],
       [3.0000e+00, 2.3000e-01, 1.0000e+00, ..., 4.0500e+00, 4.0700e+00,
        2.3100e+00],
       ...,
       [5.3938e+04, 7.0000e-01, 4.0000e+00, ..., 5.6600e+00, 5.6800e+00,
        3.5600e+00],
       [5.3939e+04, 8.6000e-01, 3.0000e+00, ..., 6.1500e+00, 6.1200e+00,
        3.7400e+00],
       [5.3940e+04, 7.5000e-01, 2.0000e+00, ..., 5.8300e+00, 5.8700e+00,
        3.6400e+00]])

In [42]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x1 = sc.fit_transform(x1)
x1

array([[-1.7320187 , -1.19816781, -0.53809897, ..., -1.58783745,
        -1.53619556, -1.57112919],
       [-1.73195448, -1.24036129,  0.43494935, ..., -1.64132529,
        -1.65877419, -1.74117497],
       [-1.73189025, -1.19816781, -1.51114729, ..., -1.49869105,
        -1.45739502, -1.74117497],
       ...,
       [ 1.73189025, -0.20662095,  1.40799767, ..., -0.06343409,
        -0.04774083,  0.03013526],
       [ 1.73195448,  0.13092691,  0.43494935, ...,  0.37338325,
         0.33750627,  0.28520393],
       [ 1.7320187 , -0.10113725, -0.53809897, ...,  0.08811478,
         0.11861587,  0.14349912]])

In [44]:
from sklearn.model_selection import train_test_split
x1_train,x1_test,y1_train,y1_test = train_test_split(x1,y1,test_size = 0.33,random_state = 4)

In [45]:
from sklearn.tree import DecisionTreeRegressor
clf = DecisionTreeRegressor(random_state = 1)
clf.fit(x1_train,y1_train)

DecisionTreeRegressor(random_state=1)

In [46]:
y1_pred = clf.predict(x1_test)
y1_pred

array([ 1978.,   728.,  4141., ...,   664.,   900., 15086.])

In [48]:
df=pd.DataFrame(y1_pred)
df

0
0       1978.0
1        728.0
2       4141.0
3       2528.0
4       4334.0
...        ...
17796   4878.0
17797   7903.0
17798    664.0
17799    900.0
17800  15086.0

[17801 rows x 1 columns]

In [49]:
datanew=pd.concat([data1,df],axis=1)
datanew

Unnamed: 0  carat  cut  color  clarity  depth  table  price     x  \
0               1   0.23    2      1        3   61.5   55.0    326  3.95   
1               2   0.21    3      1        2   59.8   61.0    326  3.89   
2               3   0.23    1      1        4   56.9   65.0    327  4.05   
3               4   0.29    3      5        5   62.4   58.0    334  4.20   
4               5   0.31    1      6        3   63.3   58.0    335  4.34   
...           ...    ...  ...    ...      ...    ...    ...    ...   ...   
53935       53936   0.72    2      0        2   60.8   57.0   2757  5.75   
53936       53937   0.72    1      0        2   63.1   55.0   2757  5.69   
53937       53938   0.70    4      0        2   62.8   60.0   2757  5.66   
53938       53939   0.86    3      4        3   61.0   58.0   2757  6.15   
53939       53940   0.75    2      0        3   62.2   55.0   2757  5.83   

          y     z       0  
0      3.98  2.43  1978.0  
1      3.84  2.31   728.0  
2      4.07  2.31  4141.0  
3      4.23  2.63  2528.0  
4      4.35  2.75  4334.0  
...     ...   ...     ...  
53935  5.76  3.50     NaN  
53936  5.75  3.61     NaN  
53937  5.68  3.56     NaN  
53938  6.12  3.74     NaN  
53939  5.87  3.64     NaN  

[53940 rows x 12 columns]

In [50]:
datanew.rename(columns={0:"Predictions"},inplace=True)
datanew

Unnamed: 0  carat  cut  color  clarity  depth  table  price     x  \
0               1   0.23    2      1        3   61.5   55.0    326  3.95   
1               2   0.21    3      1        2   59.8   61.0    326  3.89   
2               3   0.23    1      1        4   56.9   65.0    327  4.05   
3               4   0.29    3      5        5   62.4   58.0    334  4.20   
4               5   0.31    1      6        3   63.3   58.0    335  4.34   
...           ...    ...  ...    ...      ...    ...    ...    ...   ...   
53935       53936   0.72    2      0        2   60.8   57.0   2757  5.75   
53936       53937   0.72    1      0        2   63.1   55.0   2757  5.69   
53937       53938   0.70    4      0        2   62.8   60.0   2757  5.66   
53938       53939   0.86    3      4        3   61.0   58.0   2757  6.15   
53939       53940   0.75    2      0        3   62.2   55.0   2757  5.83   

          y     z  Predictions  
0      3.98  2.43       1978.0  
1      3.84  2.31        728.0  
2      4.07  2.31       4141.0  
3      4.23  2.63       2528.0  
4      4.35  2.75       4334.0  
...     ...   ...          ...  
53935  5.76  3.50          NaN  
53936  5.75  3.61          NaN  
53937  5.68  3.56          NaN  
53938  6.12  3.74          NaN  
53939  5.87  3.64          NaN  

[53940 rows x 12 columns]

In [51]:
from sklearn.metrics import r2_score  # to find the accuracy
score=r2_score(y1_test,y1_pred)
score

0.9996709533691297