In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("C:/Users/GOKUL/Downloads/weatherHistory.csv")
data

Formatted Date        Summary Precip Type  \
0      2006-04-01 00:00:00.000 +0200  Partly Cloudy        rain   
1      2006-04-01 01:00:00.000 +0200  Partly Cloudy        rain   
2      2006-04-01 02:00:00.000 +0200  Mostly Cloudy        rain   
3      2006-04-01 03:00:00.000 +0200  Partly Cloudy        rain   
4      2006-04-01 04:00:00.000 +0200  Mostly Cloudy        rain   
...                              ...            ...         ...   
96448  2016-09-09 19:00:00.000 +0200  Partly Cloudy        rain   
96449  2016-09-09 20:00:00.000 +0200  Partly Cloudy        rain   
96450  2016-09-09 21:00:00.000 +0200  Partly Cloudy        rain   
96451  2016-09-09 22:00:00.000 +0200  Partly Cloudy        rain   
96452  2016-09-09 23:00:00.000 +0200  Partly Cloudy        rain   

       Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0             9.472222                  7.388889      0.89            14.1197   
1             9.355556                  7.227778      0.86            14.2646   
2             9.377778                  9.377778      0.89             3.9284   
3             8.288889                  5.944444      0.83            14.1036   
4             8.755556                  6.977778      0.83            11.0446   
...                ...                       ...       ...                ...   
96448        26.016667                 26.016667      0.43            10.9963   
96449        24.583333                 24.583333      0.48            10.0947   
96450        22.038889                 22.038889      0.56             8.9838   
96451        21.522222                 21.522222      0.60            10.5294   
96452        20.438889                 20.438889      0.61             5.8765   

       Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
0                       251.0          15.8263         0.0   
1                       259.0          15.8263         0.0   
2                       204.0          14.9569         0.0   
3                       269.0          15.8263         0.0   
4                       259.0          15.8263         0.0   
...                       ...              ...         ...   
96448                    31.0          16.1000         0.0   
96449                    20.0          15.5526         0.0   
96450                    30.0          16.1000         0.0   
96451                    20.0          16.1000         0.0   
96452                    39.0          15.5204         0.0   

       Pressure (millibars)                           Daily Summary  
0                   1015.13       Partly cloudy throughout the day.  
1                   1015.63       Partly cloudy throughout the day.  
2                   1015.94       Partly cloudy throughout the day.  
3                   1016.41       Partly cloudy throughout the day.  
4                   1016.51       Partly cloudy throughout the day.  
...                     ...                                     ...  
96448               1014.36  Partly cloudy starting in the morning.  
96449               1015.16  Partly cloudy starting in the morning.  
96450               1015.66  Partly cloudy starting in the morning.  
96451               1015.95  Partly cloudy starting in the morning.  
96452               1016.16  Partly cloudy starting in the morning.  

[96453 rows x 12 columns]

In [3]:
data.columns

Index(['Formatted Date', 'Summary', 'Precip Type', 'Temperature (C)',
       'Apparent Temperature (C)', 'Humidity', 'Wind Speed (km/h)',
       'Wind Bearing (degrees)', 'Visibility (km)', 'Loud Cover',
       'Pressure (millibars)', 'Daily Summary'],
      dtype='object')

In [4]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

data["Precip Type"]=le.fit_transform(data["Precip Type"])

data

Formatted Date        Summary  Precip Type  \
0      2006-04-01 00:00:00.000 +0200  Partly Cloudy            0   
1      2006-04-01 01:00:00.000 +0200  Partly Cloudy            0   
2      2006-04-01 02:00:00.000 +0200  Mostly Cloudy            0   
3      2006-04-01 03:00:00.000 +0200  Partly Cloudy            0   
4      2006-04-01 04:00:00.000 +0200  Mostly Cloudy            0   
...                              ...            ...          ...   
96448  2016-09-09 19:00:00.000 +0200  Partly Cloudy            0   
96449  2016-09-09 20:00:00.000 +0200  Partly Cloudy            0   
96450  2016-09-09 21:00:00.000 +0200  Partly Cloudy            0   
96451  2016-09-09 22:00:00.000 +0200  Partly Cloudy            0   
96452  2016-09-09 23:00:00.000 +0200  Partly Cloudy            0   

       Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0             9.472222                  7.388889      0.89            14.1197   
1             9.355556                  7.227778      0.86            14.2646   
2             9.377778                  9.377778      0.89             3.9284   
3             8.288889                  5.944444      0.83            14.1036   
4             8.755556                  6.977778      0.83            11.0446   
...                ...                       ...       ...                ...   
96448        26.016667                 26.016667      0.43            10.9963   
96449        24.583333                 24.583333      0.48            10.0947   
96450        22.038889                 22.038889      0.56             8.9838   
96451        21.522222                 21.522222      0.60            10.5294   
96452        20.438889                 20.438889      0.61             5.8765   

       Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
0                       251.0          15.8263         0.0   
1                       259.0          15.8263         0.0   
2                       204.0          14.9569         0.0   
3                       269.0          15.8263         0.0   
4                       259.0          15.8263         0.0   
...                       ...              ...         ...   
96448                    31.0          16.1000         0.0   
96449                    20.0          15.5526         0.0   
96450                    30.0          16.1000         0.0   
96451                    20.0          16.1000         0.0   
96452                    39.0          15.5204         0.0   

       Pressure (millibars)                           Daily Summary  
0                   1015.13       Partly cloudy throughout the day.  
1                   1015.63       Partly cloudy throughout the day.  
2                   1015.94       Partly cloudy throughout the day.  
3                   1016.41       Partly cloudy throughout the day.  
4                   1016.51       Partly cloudy throughout the day.  
...                     ...                                     ...  
96448               1014.36  Partly cloudy starting in the morning.  
96449               1015.16  Partly cloudy starting in the morning.  
96450               1015.66  Partly cloudy starting in the morning.  
96451               1015.95  Partly cloudy starting in the morning.  
96452               1016.16  Partly cloudy starting in the morning.  

[96453 rows x 12 columns]

In [5]:
data["Precip Type"].nunique()

3

In [6]:
y = data["Precip Type"].values
y

array([0, 0, 0, ..., 0, 0, 0])

In [7]:
x = data.iloc[:,4:11].values
x

array([[7.38888889e+00, 8.90000000e-01, 1.41197000e+01, ...,
        1.58263000e+01, 0.00000000e+00, 1.01513000e+03],
       [7.22777778e+00, 8.60000000e-01, 1.42646000e+01, ...,
        1.58263000e+01, 0.00000000e+00, 1.01563000e+03],
       [9.37777778e+00, 8.90000000e-01, 3.92840000e+00, ...,
        1.49569000e+01, 0.00000000e+00, 1.01594000e+03],
       ...,
       [2.20388889e+01, 5.60000000e-01, 8.98380000e+00, ...,
        1.61000000e+01, 0.00000000e+00, 1.01566000e+03],
       [2.15222222e+01, 6.00000000e-01, 1.05294000e+01, ...,
        1.61000000e+01, 0.00000000e+00, 1.01595000e+03],
       [2.04388889e+01, 6.10000000e-01, 5.87650000e+00, ...,
        1.55204000e+01, 0.00000000e+00, 1.01616000e+03]])

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
x

array([[-0.32403547,  0.79347043,  0.47863499, ...,  1.30697578,
         0.        ,  0.10168518],
       [-0.3390971 ,  0.63999555,  0.49959388, ...,  1.30697578,
         0.        ,  0.1059598 ],
       [-0.13810226,  0.79347043, -0.99547337, ...,  1.09958576,
         0.        ,  0.10861007],
       ...,
       [ 1.04553403, -0.89475327, -0.2642411 , ...,  1.37226523,
         0.        ,  0.10621628],
       [ 0.99723295, -0.6901201 , -0.04067964, ...,  1.37226523,
         0.        ,  0.10869557],
       [ 0.89595648, -0.6389618 , -0.71369278, ...,  1.23400522,
         0.        ,  0.11049091]])

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1/3,random_state=4)

In [10]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)

LogisticRegression()

In [11]:
y_pred = lr.predict(x_test)
y_pred

array([1, 0, 0, ..., 0, 0, 0])

In [12]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
cm

array([[28099,   233,     0],
       [  217,  3443,     0],
       [  159,     0,     0]], dtype=int64)

In [13]:
from sklearn import metrics
print(metrics.accuracy_score(y_test,y_pred))

0.9810581319399085


In [14]:
from sklearn.metrics import classification_report
print (classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99     28332
           1       0.94      0.94      0.94      3660
           2       0.00      0.00      0.00       159

    accuracy                           0.98     32151
   macro avg       0.64      0.64      0.64     32151
weighted avg       0.98      0.98      0.98     32151



C:\Users\GOKUL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\GOKUL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\GOKUL\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [15]:
y_pred_all = lr.predict(x_test)
y_pred_all

array([1, 0, 0, ..., 0, 0, 0])

In [16]:
y_pred_all = pd.DataFrame(y_pred_all)
y_pred_all

0
0      1
1      0
2      0
3      0
4      0
...   ..
32146  0
32147  0
32148  0
32149  0
32150  0

[32151 rows x 1 columns]

In [17]:
new = pd.concat([data,y_pred_all],axis=1)
new

Formatted Date        Summary  Precip Type  \
0      2006-04-01 00:00:00.000 +0200  Partly Cloudy            0   
1      2006-04-01 01:00:00.000 +0200  Partly Cloudy            0   
2      2006-04-01 02:00:00.000 +0200  Mostly Cloudy            0   
3      2006-04-01 03:00:00.000 +0200  Partly Cloudy            0   
4      2006-04-01 04:00:00.000 +0200  Mostly Cloudy            0   
...                              ...            ...          ...   
96448  2016-09-09 19:00:00.000 +0200  Partly Cloudy            0   
96449  2016-09-09 20:00:00.000 +0200  Partly Cloudy            0   
96450  2016-09-09 21:00:00.000 +0200  Partly Cloudy            0   
96451  2016-09-09 22:00:00.000 +0200  Partly Cloudy            0   
96452  2016-09-09 23:00:00.000 +0200  Partly Cloudy            0   

       Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0             9.472222                  7.388889      0.89            14.1197   
1             9.355556                  7.227778      0.86            14.2646   
2             9.377778                  9.377778      0.89             3.9284   
3             8.288889                  5.944444      0.83            14.1036   
4             8.755556                  6.977778      0.83            11.0446   
...                ...                       ...       ...                ...   
96448        26.016667                 26.016667      0.43            10.9963   
96449        24.583333                 24.583333      0.48            10.0947   
96450        22.038889                 22.038889      0.56             8.9838   
96451        21.522222                 21.522222      0.60            10.5294   
96452        20.438889                 20.438889      0.61             5.8765   

       Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
0                       251.0          15.8263         0.0   
1                       259.0          15.8263         0.0   
2                       204.0          14.9569         0.0   
3                       269.0          15.8263         0.0   
4                       259.0          15.8263         0.0   
...                       ...              ...         ...   
96448                    31.0          16.1000         0.0   
96449                    20.0          15.5526         0.0   
96450                    30.0          16.1000         0.0   
96451                    20.0          16.1000         0.0   
96452                    39.0          15.5204         0.0   

       Pressure (millibars)                           Daily Summary    0  
0                   1015.13       Partly cloudy throughout the day.  1.0  
1                   1015.63       Partly cloudy throughout the day.  0.0  
2                   1015.94       Partly cloudy throughout the day.  0.0  
3                   1016.41       Partly cloudy throughout the day.  0.0  
4                   1016.51       Partly cloudy throughout the day.  0.0  
...                     ...                                     ...  ...  
96448               1014.36  Partly cloudy starting in the morning.  NaN  
96449               1015.16  Partly cloudy starting in the morning.  NaN  
96450               1015.66  Partly cloudy starting in the morning.  NaN  
96451               1015.95  Partly cloudy starting in the morning.  NaN  
96452               1016.16  Partly cloudy starting in the morning.  NaN  

[96453 rows x 13 columns]

In [19]:
new.rename(columns={0:"Rain Predictions"},inplace=True)
new

Formatted Date        Summary  Precip Type  \
0      2006-04-01 00:00:00.000 +0200  Partly Cloudy            0   
1      2006-04-01 01:00:00.000 +0200  Partly Cloudy            0   
2      2006-04-01 02:00:00.000 +0200  Mostly Cloudy            0   
3      2006-04-01 03:00:00.000 +0200  Partly Cloudy            0   
4      2006-04-01 04:00:00.000 +0200  Mostly Cloudy            0   
...                              ...            ...          ...   
96448  2016-09-09 19:00:00.000 +0200  Partly Cloudy            0   
96449  2016-09-09 20:00:00.000 +0200  Partly Cloudy            0   
96450  2016-09-09 21:00:00.000 +0200  Partly Cloudy            0   
96451  2016-09-09 22:00:00.000 +0200  Partly Cloudy            0   
96452  2016-09-09 23:00:00.000 +0200  Partly Cloudy            0   

       Temperature (C)  Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0             9.472222                  7.388889      0.89            14.1197   
1             9.355556                  7.227778      0.86            14.2646   
2             9.377778                  9.377778      0.89             3.9284   
3             8.288889                  5.944444      0.83            14.1036   
4             8.755556                  6.977778      0.83            11.0446   
...                ...                       ...       ...                ...   
96448        26.016667                 26.016667      0.43            10.9963   
96449        24.583333                 24.583333      0.48            10.0947   
96450        22.038889                 22.038889      0.56             8.9838   
96451        21.522222                 21.522222      0.60            10.5294   
96452        20.438889                 20.438889      0.61             5.8765   

       Wind Bearing (degrees)  Visibility (km)  Loud Cover  \
0                       251.0          15.8263         0.0   
1                       259.0          15.8263         0.0   
2                       204.0          14.9569         0.0   
3                       269.0          15.8263         0.0   
4                       259.0          15.8263         0.0   
...                       ...              ...         ...   
96448                    31.0          16.1000         0.0   
96449                    20.0          15.5526         0.0   
96450                    30.0          16.1000         0.0   
96451                    20.0          16.1000         0.0   
96452                    39.0          15.5204         0.0   

       Pressure (millibars)                           Daily Summary  \
0                   1015.13       Partly cloudy throughout the day.   
1                   1015.63       Partly cloudy throughout the day.   
2                   1015.94       Partly cloudy throughout the day.   
3                   1016.41       Partly cloudy throughout the day.   
4                   1016.51       Partly cloudy throughout the day.   
...                     ...                                     ...   
96448               1014.36  Partly cloudy starting in the morning.   
96449               1015.16  Partly cloudy starting in the morning.   
96450               1015.66  Partly cloudy starting in the morning.   
96451               1015.95  Partly cloudy starting in the morning.   
96452               1016.16  Partly cloudy starting in the morning.   

       Rain Predictions  
0                   1.0  
1                   0.0  
2                   0.0  
3                   0.0  
4                   0.0  
...                 ...  
96448               NaN  
96449               NaN  
96450               NaN  
96451               NaN  
96452               NaN  

[96453 rows x 13 columns]

In [35]:
y_pred_test = [[-0.32403547,  0.79347043,  0.47863499,  0.591256  ,  1.30697578,
        0.        ,  0.10168518]]
y_pred_test

[[-0.32403547, 0.79347043, 0.47863499, 0.591256, 1.30697578, 0.0, 0.10168518]]

In [36]:
w=lr.predict(y_pred_test)
w

array([0])

In [37]:
x[0]

array([-0.32403547,  0.79347043,  0.47863499,  0.591256  ,  1.30697578,
        0.        ,  0.10168518])